Chapter-2: 2-16.c 2-17a.c 2-17b.c 2-17c.c 2-18.c 2-19.c 2-20.c 2-21.c 2-22.c\
           2-23.c 2-24.c 2-25.c 2-26.c 2-27.c 2-29.c 2-30.c 2-31.c 2-32.c
	cd ../bin && mkdir Chapter-2 && cd ../Chapter-2
	gcc -o ../bin/Chapter-2/2-16 2-16.c
	gcc -o ../bin/Chapter-2/2-17a 2-17a.c
	gcc -o ../bin/Chapter-2/2-17b 2-17b.c
	gcc -o ../bin/Chapter-2/2-17c 2-17c.c
	gcc -o ../bin/Chapter-2/2-18 2-18.c
	gcc -o ../bin/Chapter-2/2-19 2-19.c
	gcc -o ../bin/Chapter-2/2-20 2-20.c
	gcc -o ../bin/Chapter-2/2-21 2-21.c
	gcc -o ../bin/Chapter-2/2-22 2-22.c
	gcc -o ../bin/Chapter-2/2-23 2-23.c
	gcc -o ../bin/Chapter-2/2-24 2-24.c
	gcc -o ../bin/Chapter-2/2-25 2-25.c
	gcc -o ../bin/Chapter-2/2-26 2-26.c
	gcc -o ../bin/Chapter-2/2-27 2-27.c
	gcc -o ../bin/Chapter-2/2-29 2-29.c
	gcc -o ../bin/Chapter-2/2-30 2-30.c
	gcc -o ../bin/Chapter-2/2-31 2-31.c
	gcc -o ../bin/Chapter-2/2-32 2-32.c

.PHONY: clean
clean:
	rm -r ../bin/Chapter-2/
