Chapter-2: 3-13.c 3-17.c 3-18.c 3-19.c 3-20.c 3-21.c 3-22.c 3-23.c 3-24.c\
           3-25.c 3-26.c 3-27.c 3-29.c 3-30.c 3-33.c 3-34.c 3-35.c 3-36.c\
           3-37.c 3-38.c 3-41.c 3-42.c 3-43.c 3-45.c 3-46a.c 3-47.c 
	cd ../bin && mkdir Chapter-3 && cd ../Chapter-3
	gcc -o ../bin/Chapter-3/3-13 3-13.c
	gcc -o ../bin/Chapter-3/3-17 3-17.c
	gcc -o ../bin/Chapter-3/3-18 3-18.c
	gcc -o ../bin/Chapter-3/3-19 3-19.c
	gcc -o ../bin/Chapter-3/3-20 3-20.c
	gcc -o ../bin/Chapter-3/3-21 3-21.c
	gcc -o ../bin/Chapter-3/3-22 3-22.c
	gcc -o ../bin/Chapter-3/3-23 3-23.c
	gcc -o ../bin/Chapter-3/3-24 3-24.c
	gcc -o ../bin/Chapter-3/3-25 3-25.c
	gcc -o ../bin/Chapter-3/3-26 3-26.c
	gcc -o ../bin/Chapter-3/3-27 3-27.c
	gcc -o ../bin/Chapter-3/3-29 3-29.c
	gcc -o ../bin/Chapter-3/3-30 3-30.c
	gcc -o ../bin/Chapter-3/3-33 3-33.c
	gcc -o ../bin/Chapter-3/3-34 3-34.c
	gcc -o ../bin/Chapter-3/3-35 3-35.c
	gcc -o ../bin/Chapter-3/3-36 3-36.c
	gcc -o ../bin/Chapter-3/3-37 3-37.c
	gcc -o ../bin/Chapter-3/3-38 3-38.c
	gcc -o ../bin/Chapter-3/3-41 3-41.c
	gcc -o ../bin/Chapter-3/3-42 3-42.c
	gcc -o ../bin/Chapter-3/3-43 3-43.c
	gcc -o ../bin/Chapter-3/3-45 3-45.c
	gcc -o ../bin/Chapter-3/3-46a 3-46a.c
	gcc -o ../bin/Chapter-3/3-47 3-47.c

.PHONY: clean
clean:
	rm -r ../bin/Chapter-3
